Move the software version to resource page.
tmolitor-stud-tu/Monal pull request #38
Opened 2020-10-07 04:17 UTC by poormusic2001

1. Move software version functions.
2. Add the db access condition with resource.

2020-10-07 06:03 UTC, Echolon commented
Thank you Jim @poormusic2001 

There is a build error unfortunately 🙁 Lets see reviewers will say

2020-10-08 04:52 UTC, tmolitor-stud-tu commented on Monal/Classes/DataLayer.m
> +-(NSArray*) softwareVersionInfoForAccount:(NSString*)account contact:(NSString*)contact andResource:(NSString*)resource
I don't like that method name
`getSoftwareVersionInfoForContact:andAccount:` would be better.

2020-10-08 04:53 UTC, tmolitor-stud-tu commented on Monal/Classes/DataLayer.h
> +-(void) setSoftwareVersionInfoForAppName:(NSString*)appName appVersion:(NSString*)appVersion platformOS:(NSString*)platformOS withAccount:(NSString*)account contact:(NSString*)contact andResource:(NS
I don't like this method name.
`setSoftwareVersionInfoForContact:resource:andAccount:withAppName:appVersion:andPlatformOS:` would be much better.

2020-10-08 04:55 UTC, tmolitor-stud-tu commented on Monal/Classes/MLIQProcessor.m
> +                                                              userInfo:@{iqNode.fromResource:@{
Don't use something that could be nil as key.
Just set the `fromResource` as one extra key in your `userInfo` dictionary.

2020-10-08 04:57 UTC, tmolitor-stud-tu commented on Monal/Classes/MLXMPPManager.m
> +-(void) getEntitySoftWareVersion:(MLContact *) contact andResource:(NSString*) resource
name again: `getEntitySoftWareVersionForContact:andResource:`

2020-10-08 04:58 UTC, tmolitor-stud-tu requested changes
See my inline comments

2020-10-08 04:59 UTC, tmolitor-stud-tu commented
@Echolon the build failed because our tests used in the CI are not yet updated to the new parser.

2020-10-15 01:34 UTC, merged