Feature request: Search function #482
tmolitor-stud-tu/Monal pull request #39
Opened 2020-10-15 14:18 UTC by poormusic2001

Add search history chat function.

2020-10-15 17:44 UTC, tmolitor-stud-tu commented on Monal/Classes/DataLayer.m
> +    [result enumerateObjectsUsingBlock:^(id  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
can you use a normal `for...in...` instead? that would make the code more readable, e.g.: `for(NSDictionary* dic in result)`

2020-10-15 17:45 UTC, tmolitor-stud-tu commented on Monal/Classes/DataLayer.m
> +    NSString* query = [NSString stringWithFormat:@"select actual_from as af, message_from, message_to, account_id, message, timestamp  as thetime0, message_history_id, sent, messageid, messageType, r
no one needs `NSString stringWithFormat:`, thats a relict from long time ago when monal did not use prepared queries. New code should avoid that (and old one should be changed accordingly eventually)

2020-10-15 17:46 UTC, tmolitor-stud-tu commented on Monal/Classes/DataLayer.m
> +    [result enumerateObjectsUsingBlock:^(id  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
same as above: use `for...in...`

2020-10-15 17:47 UTC, tmolitor-stud-tu commented on Monal/Classes/DataLayer.m
> +    NSNumber* historyId = (NSNumber*)[self.db executeScalar:@"SELECT message_history_id FROM message_history WHERE account_id=? AND message_from=? AND messageid=?;" andArguments:@[accountNo, contact,
you don't need the `NSNumber*` cast anymore, all `MLSQLite` methods return an `id` instead of `NSObject` now :)

2020-10-15 17:51 UTC, tmolitor-stud-tu commented on Monal/Classes/MLSearchViewController.m
> +    if (yAxis > 50) {//I don't know why there is 50 difference in the first time when searchbar shows ...need to figure out.
maybe because the top bar can be made bigger by pulling it down

2020-10-15 17:58 UTC, tmolitor-stud-tu commented on Monal/Classes/chatViewController.m
> +	//Init search button item.
one space too much ;)

2020-10-15 18:50 UTC, tmolitor-stud-tu commented on Monal/Classes/chatViewController.m
> +            //Set DBId for new message. It is nil when the notification come in.
better use the id coming from the db, I modified the code to return the history id in the `kMonalNewMessageNotice` :)
It's dictionary entry is named `historyId`, see #3d66882231d8d47caf39c7c8894443157833d2ea

2020-10-15 19:06 UTC, tmolitor-stud-tu requested changes
I added some comments you should resolve.

2020-10-16 17:23 UTC, tmolitor-stud-tu commented
can you rebase this?

2020-10-19 06:04 UTC, poormusic2001 commented
I updated the code.

2020-10-19 15:54 UTC, tmolitor-stud-tu approved these changes

2020-10-19 15:54 UTC, merged