Add FileTransfer UI and icon links license.
tmolitor-stud-tu/Monal pull request #59
Opened 2021-01-31 04:09 UTC by poormusic2001

2021-01-31 05:46 UTC, tmolitor-stud-tu commented on Monal/Classes/MLFiletransfer.m
> ++(BOOL) checkFileRequest:(NSNumber*) historyId
This name does not really reflect what this method is doing.
I would suggest something like `isFileforHistoryIdInTransfer` or `isFileforHistoryIDInTransfer`

2021-01-31 05:48 UTC, FriedrichAltheide requested changes

2021-01-31 05:48 UTC, FriedrichAltheide commented on Monal/opensource.html
> +        <hr>
Please add a link to the main page I icons8.com above the used icon link section

2021-01-31 05:48 UTC, tmolitor-stud-tu commented on Monal/Classes/MonalAppDelegate.m
> +    AVAudioSession *audioSession = AVAudioSession.sharedInstance;
Why is this here?
Shouldn't the microphone access be requested only when users try to record some audio?

2021-01-31 05:52 UTC, FriedrichAltheide commented on Monal/Classes/chatViewController.m
> +    NSString *images = @"public.image";
- should be const
- Please move them to MLConstants.h

2021-01-31 05:56 UTC, tmolitor-stud-tu commented on Monal/Classes/chatViewController.m
> +                    else if([fileType hasPrefix:@"text/"])
Don't we need a general `else` case setting `fileTransferCell.transferStatus = transferFileTypeNeedDowndload;`? The case for application and text can be summarized into this general case as well.

2021-01-31 05:59 UTC, FriedrichAltheide commented on Monal/Classes/chatViewController.m
> +             || [info[@"mimeType"] isEqual:@"application/pdf"]//.pdf
Please reuse the const names from MLConstants.h

2021-01-31 06:05 UTC, tmolitor-stud-tu commented on Monal/Classes/chatViewController.m
> +    else if ([info[@"mimeType"] hasPrefix:@"text/"]
Filetransfers and links are distinct xmpp "types". All filetransfers should always have a download button (e.g. download cell).

That means you don't need this lengthy check for supported types but a general `else` case supporting all file types that have no special handling (like video, audio or image filetransfers do).

2021-02-01 01:22 UTC, poormusic2001 commented on Monal/localization/Base.lproj/Main.storyboard
> +        <systemColor name="groupTableViewBackgroundColor">
I use Xcode 12.2 beta 4, the newest version is 12.4. Do you use the Xcode 12.4 to develop?

2021-02-01 01:23 UTC, poormusic2001 commented on Monal/Classes/MLFiletransfer.m
> ++(BOOL) checkFileRequest:(NSNumber*) historyId
I will modify it later.

2021-02-01 01:24 UTC, poormusic2001 commented on Monal/opensource.html
> +        <hr>
Can you tell me... where is it?

2021-02-01 01:34 UTC, tmolitor-stud-tu commented on Monal/opensource.html
> +        <hr>
just add `Icons from <a href="https://icons8.com/">Icons8</a>:` on the top

2021-02-01 01:35 UTC, tmolitor-stud-tu commented on Monal/localization/Base.lproj/Main.storyboard
> +        <systemColor name="groupTableViewBackgroundColor">
yes we do (that version does not add those spurious color stuff to storyboards anymore)

2021-02-01 03:09 UTC, poormusic2001 commented on Monal/localization/Base.lproj/Main.storyboard
> +        <systemColor name="groupTableViewBackgroundColor">
Got it.

2021-02-01 03:13 UTC, poormusic2001 commented on Monal/opensource.html
> +        <hr>
ok

2021-02-01 03:41 UTC, poormusic2001 commented on Monal/Classes/chatViewController.m
> +             || [info[@"mimeType"] isEqual:@"application/pdf"]//.pdf
ok

2021-02-01 03:58 UTC, poormusic2001 commented on Monal/Classes/MonalAppDelegate.m
> +    AVAudioSession *audioSession = AVAudioSession.sharedInstance;
I misuse to AVPlayer. I will remove it.

2021-02-06 21:22 UTC, tmolitor-stud-tu commented
Please create a new pull request over at https://github.com/monal-im/Monal once you resolved these issues.
We are currently in the process of merging my repo and upstream.

2021-02-06 21:22 UTC, closed without merging

2021-02-09 03:23 UTC, poormusic2001 commented
> Please create a new pull request over at https://github.com/monal-im/Monal once you resolved these issues.
> We are currently in the process of merging my repo and upstream.

ok

2021-02-13 18:18 UTC, tmolitor-stud-tu commented
We solved the review comments ourselves and merged your pull request into https://github.com/monal-im/Monal